apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dapr-app
  namespace: dapr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "test-app"
        dapr.io/app-port: "8080"
    spec:
      containers:
        - name: test-app
          image: nginx:alpine
          ports:
            - containerPort: 8080
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo 'Test app running'; sleep 30; done"]