---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-producer
  namespace: knative-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-producer
  template:
    metadata:
      labels:
        app: event-producer
    spec:
      containers:
      - name: producer
        image: python:3.11-slim
        command: ["/bin/bash"]
        args: ["/app/startup.sh"]
        env:
        - name: BROKER_URL
          value: http://broker-ingress.knative-eventing.svc.cluster.local/knative-demo/default
        - name: SOURCE
          value: "knative-demo-producer"
        - name: SEND_INTERVAL
          value: "10"  # 每10秒发送一次事件
        volumeMounts:
        - name: producer-code
          mountPath: /app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: producer-code
        configMap:
          name: producer-config
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: event-producer-service
  namespace: knative-demo
spec:
  selector:
    app: event-producer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
  namespace: knative-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-consumer
  template:
    metadata:
      labels:
        app: event-consumer
    spec:
      containers:
      - name: consumer
        image: python:3.11-slim
        command: ["/bin/bash"]
        args: ["/app/startup.sh"]
        ports:
        - containerPort: 8080
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: PROCESSING_DELAY
          value: "1"
        - name: PORT
          value: "8080"
        volumeMounts:
        - name: consumer-code
          mountPath: /app
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 30
      volumes:
      - name: consumer-code
        configMap:
          name: consumer-config
          defaultMode: 0755

---
apiVersion: v1
kind: Service
metadata:
  name: event-consumer-service
  namespace: knative-demo
spec:
  selector:
    app: event-consumer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP 