# 简单的 NATS 测试部署

---
# 1. 单节点 NATS (开发测试用)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-server
  namespace: knative-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.9.23-alpine
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8222
          name: monitor
        command:
        - nats-server
        - --jetstream
        - --store_dir=/data
        - --max_file_store=1GB
        - --max_memory_store=256MB
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: data
        emptyDir: {}

---
# 2. NATS Service
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: knative-demo
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitor
    port: 8222
    targetPort: 8222

---
# 3. NATS 测试客户端
apiVersion: v1
kind: Pod
metadata:
  name: nats-test
  namespace: knative-demo
spec:
  containers:
  - name: test
    image: natsio/nats-box:latest
    command: ["sleep", "3600"]
    env:
    - name: NATS_URL
      value: "nats://nats-service:4222"

---
# 测试命令示例:
# 
# # 进入测试 Pod
# kubectl exec -it nats-test -n knative-demo -- sh
# 
# # 订阅消息
# nats sub test.subject
# 
# # 发布消息 (在另一个终端)
# nats pub test.subject "Hello NATS!"
# 
# # 查看 JetStream 状态
# nats stream ls
# nats stream info
# 
# # 创建持久化流
# nats stream add test-stream --subjects="events.*" --retention=limits --max-age=1h 